name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  http: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gallery_saver:
    path: ../

flutter:
  uses-material-design: true
